kind: ReplicationController
apiVersion: v1
metadata:
  name: outyet-v7
spec:
  replicas: 3
  selector:
    name: outyet
    version: "7"
  template:
    metadata:
      labels:
        name: outyet
        version: "7"
    spec:
      containers:
        - image: gcr.io/alpha-connect-four/quiklyrics:v5
          name: quiklyrics
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          env:
            - name: GET_HOSTS_FROM
              value: dns
              # If your cluster config does not include a dns service, then to
              # instead access environment variables to find service host
              # info, comment out the 'value: dns' line above, and uncomment the
              # line below.
              # value: env